version: "3"

volumes:
  kestra-data:
    driver: local
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  kestra:
    image: kestra/kestra:latest
    pull_policy: always
    stop_grace_period: 6m
    user: "root"
    command: server standalone --worker-thread 2
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    environment:
      JAVA_OPTS: "-Xmx4096m -XX:-DoEscapeAnalysis"
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          tutorialFlows:
            enabled: false
          worker:
            threads: 2
          plugins:
            defaults:
              - type: io.kestra.plugin.scripts.python.Script
                values:
                  taskRunner:
                    type: io.kestra.plugin.core.runner.Process
          server:
            basic-auth:
              username: admin@kestra.io
              password: Admin1234!
              open-urls:
                - "/api/v1/executions/webhook/"
                - "/api/v1/main/executions/webhook/"
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
            runners:
              default: io.kestra.plugin.core.runner.Process
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          url: http://localhost:8080/
          variables:
            globals:
              gemini-api-key: "${GEMINI_API_KEY}"
              slack-webhook-url: "${SLACK_WEBHOOK_URL:-}"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
